
CREATE DATABASE IF NOT EXISTS office;

USE office;

CREATE TABLE IF NOT EXISTS address(ID INT NOT NULL AUTO_INCREMENT, LINE1 VARCHAR(255), LINE2 VARCHAR(255), CITY VARCHAR(100), EMPLOYEE_STATE VARCHAR(100), COUNTRY VARCHAR(100), ZIPCODE VARCHAR(10), PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS departments (ID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR(150), PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS employees (ID INT NOT NULL AUTO_INCREMENT, NAME VARCHAR(255), EMAIL VARCHAR(500), ADDRESS_ID INT, DEPARTMENT_ID INT, PRIMARY KEY (ID), FOREIGN KEY (ADDRESS_ID) REFERENCES address(ID), FOREIGN KEY (DEPARTMENT_ID) REFERENCES departments(ID));

INSERT INTO departments (NAME) VALUES("HTMS");
INSERT INTO departments (NAME) VALUES("BFSI");
INSERT INTO departments (NAME) VALUES("DIGITAL");
INSERT INTO departments (NAME) VALUES("CSG");
INSERT INTO departments (NAME) VALUES("TTH");
INSERT INTO departments (NAME) VALUES("IGG");